version: '3.3'

services:
  words:
    image: awesome-sauce:1
    ports:
     - "82:80"
    deploy:
      replicas: 5
      endpoint_mode: dnsrr
      resources:
        limits:
          memory: 50M
        reservations:
          memory: 50M

  db:
    image: dockersamples/k8s-wordsmith-db